ALTER TABLE `SEQ_RVS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_PSHS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_DRS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_PGS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_DTS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_PDSS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_PDTS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_OMCS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_DCS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_DPS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_DSS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_PSDS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_AQES` ENGINE = InnoDB; 

ALTER TABLE `SEQ_AES` ENGINE = InnoDB; 

ALTER TABLE `SEQ_BPS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_DTPS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_PES` ENGINE = InnoDB; 

ALTER TABLE `SEQ_FLMS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_SIS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_BKS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_FLS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_FPS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_FTS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_SES` ENGINE = InnoDB; 

ALTER TABLE `SEQ_BSES` ENGINE = InnoDB; 

ALTER TABLE `SEQ_FCS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_AFS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_BHS` ENGINE = InnoDB; 

ALTER TABLE `SEQ_DVS` ENGINE = InnoDB; 
