
ALTER TABLE `APPLICATION_EXECUTABLES` MODIFY `APP_EXEC_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `RELEASE_VERSIONS` MODIFY `RELEASE_VERSION_ID` INTEGER NOT NULL AUTO_INCREMENT;
    

ALTER TABLE `PROCESSED_DATASETS` MODIFY `PROCESSED_DS_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `BRANCH_HASHES` MODIFY `BRANCH_HASH_ID` INTEGER NOT NULL AUTO_INCREMENT;
    
ALTER TABLE `FILE_TYPES` MODIFY `FILE_TYPE_ID` INTEGER NOT NULL NULL AUTO_INCREMENT;
    
ALTER TABLE `PHYSICS_GROUPS` MODIFY `PHYSICS_GROUP_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `PRIMARY_DS_TYPES` MODIFY `PRIMARY_DS_TYPE_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `DATASET_TYPES` MODIFY `DATASET_TYPE_ID` INTEGER NOT NULL AUTO_INCREMENT;
    
ALTER TABLE `PARAMETER_SET_HASHES` MODIFY `PARAMETER_SET_HASH_ID` INTEGER NOT NULL AUTO_INCREMENT;
   
ALTER TABLE `DBS_VERSIONS` MODIFY `DBS_VERSION_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `SITES` MODIFY `SITE_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `OUTPUT_MODULE_CONFIGS` MODIFY `OUTPUT_MOD_CONFIG_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `DATA_TIERS` MODIFY `DATA_TIER_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `PRIMARY_DATASETS` MODIFY `PRIMARY_DS_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `DATASETS` MODIFY `DATASET_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `BLOCKS` MODIFY `BLOCK_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `BLOCK_PARENTS` MODIFY `BLOCK_PARENT_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `FILES` MODIFY `FILE_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `DATASET_OUTPUT_MOD_CONFIGS` MODIFY `DS_OUTPUT_MOD_CONF_ID` INTEGER NOT NULL AUTO_INCREMENT; 

ALTER TABLE `DATASET_PARENTS` MODIFY `DATASET_PARENT_ID` INTEGER NOT NULL AUTO_INCREMENT; 

ALTER TABLE `DATASET_RUNS` MODIFY `DATASET_RUN_ID` INTEGER NOT NULL AUTO_INCREMENT; 

ALTER TABLE `FILE_OUTPUT_MOD_CONFIGS` MODIFY `FILE_OUTPUT_CONFIG_ID` INTEGER NOT NULL AUTO_INCREMENT; 

ALTER TABLE `ASSOCIATED_FILES` MODIFY `ASSOCATED_FILE_ID` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `FILE_PARENTS` MODIFY `FILE_PARENT_ID` INTEGER NOT NULL AUTO_INCREMENT; 

ALTER TABLE `FILE_LUMIS` MODIFY  `FILE_LUMI_ID` INTEGER NOT NULL AUTO_INCREMENT; 
    
ALTER TABLE `ACQUISITION_ERAS` MODIFY `ACQUISITION_ERA_ID` INTEGER NOT NULL AUTO_INCREMENT; 

ALTER TABLE `PROCESSING_ERAS` MODIFY  `PROCESSING_ERA_ID` INTEGER NOT NULL AUTO_INCREMENT;
    
ALTER TABLE `STORAGE_ELEMENTS` MODIFY  `SE_ID` INTEGER NOT NULL AUTO_INCREMENT;
   
ALTER TABLE `BLOCK_STORAGE_ELEMENTS` MODIFY `BLOCK_SE_ID` INTEGER NOT NULL AUTO_INCREMENT;

##

ALTER TABLE `APPLICATION_EXECUTABLES` ENGINE = InnoDB;

ALTER TABLE `RELEASE_VERSIONS` ENGINE = InnoDB;
    
ALTER TABLE `PROCESSED_DATASETS` ENGINE = InnoDB;

ALTER TABLE `BRANCH_HASHES` ENGINE = InnoDB;
    
ALTER TABLE `FILE_TYPES` ENGINE = InnoDB;
    
ALTER TABLE `PHYSICS_GROUPS` ENGINE = InnoDB;

ALTER TABLE `PRIMARY_DS_TYPES` ENGINE = InnoDB;

ALTER TABLE `DATASET_TYPES` ENGINE = InnoDB;
    
ALTER TABLE `PARAMETER_SET_HASHES` ENGINE = InnoDB;
   
ALTER TABLE `DBS_VERSIONS` ENGINE = InnoDB;

ALTER TABLE `SITES` ENGINE = InnoDB;

ALTER TABLE `OUTPUT_MODULE_CONFIGS` ENGINE = InnoDB;

ALTER TABLE `DATA_TIERS` ENGINE = InnoDB;

ALTER TABLE `PRIMARY_DATASETS` ENGINE = InnoDB;

ALTER TABLE `DATASETS`  ENGINE = InnoDB;

ALTER TABLE `BLOCKS` ENGINE = InnoDB;

ALTER TABLE `BLOCK_PARENTS` ENGINE = InnoDB;

ALTER TABLE `FILES` ENGINE = InnoDB;

ALTER TABLE `DATASET_OUTPUT_MOD_CONFIGS` ENGINE = InnoDB; 

ALTER TABLE `DATASET_PARENTS` ENGINE = InnoDB; 

ALTER TABLE `DATASET_RUNS` ENGINE = InnoDB; 

ALTER TABLE `FILE_OUTPUT_MOD_CONFIGS` ENGINE = InnoDB; 

ALTER TABLE `ASSOCIATED_FILES` ENGINE = InnoDB;

ALTER TABLE `FILE_PARENTS` ENGINE = InnoDB; 

ALTER TABLE `FILE_LUMIS` ENGINE = InnoDB; 
    
ALTER TABLE `ACQUISITION_ERAS` ENGINE = InnoDB; 

ALTER TABLE `PROCESSING_ERAS` ENGINE = InnoDB;
    
ALTER TABLE `STORAGE_ELEMENTS` ENGINE = InnoDB;
   
ALTER TABLE `BLOCK_STORAGE_ELEMENTS` ENGINE = InnoDB;




