ALTER TABLE `MIGRATION_BLOCKS` ENGINE = InnoDB;

ALTER TABLE `MIGRATION_REQUESTS` ENGINE = InnoDB;

ALTER TABLE `FILE_BUFFERS` ENGINE = InnoDB;

ALTER TABLE `COMPONENT_STATUS` ENGINE = InnoDB;

ALTER TABLE `BLOCK_SITES` ENGINE = InnoDB;

ALTER TABLE `APPLICATION_EXECUTABLES` ENGINE = InnoDB;

ALTER TABLE `RELEASE_VERSIONS` ENGINE = InnoDB;
    
ALTER TABLE `PROCESSED_DATASETS` ENGINE = InnoDB;

ALTER TABLE `BRANCH_HASHES` ENGINE = InnoDB;
    
ALTER TABLE `FILE_DATA_TYPES` ENGINE = InnoDB;
    
ALTER TABLE `PHYSICS_GROUPS` ENGINE = InnoDB;

ALTER TABLE `PRIMARY_DS_TYPES` ENGINE = InnoDB;

ALTER TABLE `DATASET_ACCESS_TYPES` ENGINE = InnoDB;
    
ALTER TABLE `PARAMETER_SET_HASHES` ENGINE = InnoDB;
   
ALTER TABLE `DBS_VERSIONS` ENGINE = InnoDB;

ALTER TABLE `SITES` ENGINE = InnoDB;

ALTER TABLE `OUTPUT_MODULE_CONFIGS` ENGINE = InnoDB;

ALTER TABLE `DATA_TIERS` ENGINE = InnoDB;

ALTER TABLE `PRIMARY_DATASETS` ENGINE = InnoDB;

ALTER TABLE `DATASETS`  ENGINE = InnoDB;

ALTER TABLE `BLOCKS` ENGINE = InnoDB;

ALTER TABLE `BLOCK_PARENTS` ENGINE = InnoDB;

ALTER TABLE `FILES` ENGINE = InnoDB;

ALTER TABLE `DATASET_OUTPUT_MOD_CONFIGS` ENGINE = InnoDB; 

ALTER TABLE `DATASET_PARENTS` ENGINE = InnoDB; 

ALTER TABLE `DATASET_RUNS` ENGINE = InnoDB; 

ALTER TABLE `FILE_OUTPUT_MOD_CONFIGS` ENGINE = InnoDB; 

ALTER TABLE `ASSOCIATED_FILES` ENGINE = InnoDB;

ALTER TABLE `FILE_PARENTS` ENGINE = InnoDB; 

ALTER TABLE `FILE_LUMIS` ENGINE = InnoDB; 
    
ALTER TABLE `ACQUISITION_ERAS` ENGINE = InnoDB; 

ALTER TABLE `PROCESSING_ERAS` ENGINE = InnoDB;
