INSERT INTO ACQUISITION_ERAS(ACQUSITION_ERA_NAME) VALUES (?);
INSERT INTO APPLICATION_EXECUTABLES(APP_NAME) VALUES (?);
INSERT INTO ASSOCIATED_FILES(THIS_FILE_ID, ASSOCATED_FILE) VALUES (?, ?);
INSERT INTO BLOCKS(BLOCK_NAME, PATH_ID, OPEN_FOR_WRITING, ORIGIN_SITE, BLOCK_SIZE, FILE_COUNT, CREATION_DATE, CREATE_BY, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO BLOCK_PARENTS(THIS_BLOCK_ID, PARENT_BLOCK_ID) VALUES (?, ?);
INSERT INTO BLOCK_STORAGE_ELEMENTS(SE_ID, BLOCK_ID) VALUES (?, ?);
INSERT INTO BRANCH_HASHES(HASH, CONTENT) VALUES (?, ?);
INSERT INTO DATA_TIERS(DATA_TIER_NAME, CREATION_DATE, CREATE_BY) VALUES (?, ?, ?);
INSERT INTO DBS_VERSIONS(SCHEMA_VERSION, DBS_RELEASE_VERSION, INSTANCE_NAME, INSTANCE_TYPE, CREATION_DATE, LAST_MODIFICATION_DATE) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO FILES(LOGICAL_FILE_NAME, IS_FILE_VALID, PATH_ID, BLOCK_ID, FILE_TYPE_ID, CHECK_SUM, EVENT_COUNT, FILE_SIZE, BRANCH_HASH_ID, ADLER32, MD5, AUTO_CROSS_SECTION, CREATION_DATE, CREATE_BY, LASTMODIFICATIONDATE, LAST_MODIFIED_BY) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO FILE_LUMIS(RUN_NUM, LUMI_SECTION_NUM, FILE_ID) VALUES (?, ?, ?);
INSERT INTO FILE_PARENTS(THIS_FILE_ID, PARENT_FILE_ID) VALUES (?, ?);
INSERT INTO FILE_PROCESS_CONFIGS(FILE_ID, PROCESS_CONFIG_ID) VALUES (?, ?);
INSERT INTO FILE_TYPES(FILE_TYPE) VALUES (?);
INSERT INTO PARAMETER_SET_HASHES(HASH, NAME) VALUES (?, ?);
INSERT INTO PATHS(PATH_NAME, IS_PATH_VAILD, PRIMARY_DS_ID, PROCESSED_DS_ID, DATA_TIER_ID, PATH_TYPE_ID, ACQUISITION_ERA_ID, PROCESSING_ERA_ID, PHYSICS_GROUP_ID, XTCROSSSECTION, GLOBAL_TAG, CREATIONDATE, CREATEBY, LASTMODIFICATIONDATE, LASTMODIFIEDBY) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO PATH_PARENTS(THIS_PATH_ID, PARENT_PATH_ID) VALUES (?, ?);
INSERT INTO PATH_PROCESS_CONFIGS(PATH_ID, PROCESS_CONFIG_ID) VALUES (?, ?);
INSERT INTO PATH_RUNS(PATH_ID, RUN_NUMBER, COMPLETE, EVENT_COUNT, LUMI_SECTION_COUNT, CREATION_DATE, CREATE_BY) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO PATH_TYPES(PATH_TYPE) VALUES (?);
INSERT INTO PHYSICS_GROUPS(PHYSICS_GROUP_NAME, PHYSICS_GROUP_CONVENER) VALUES (?, ?);
INSERT INTO PRIMARY_DATASETS(PRIMARY_DS_NAME, PRIMARY_DS_TYPE_ID, CREATION_DATE, CREATE_BY) VALUES (?, ?, ?, ?);
INSERT INTO PRIMARY_DS_TYPES(PRIMARY_DS_TYPE) VALUES (?);
INSERT INTO PROCESSED_DATASETS(PROCESSED_DS_NAME) VALUES (?);
INSERT INTO PROCESSING_ERAS(PROCESSING_ERA_NAME) VALUES (?);
INSERT INTO PROCESS_CONFIGURATIONS(APP_EXEC_ID, RELEASE_VERSION_ID, PARAMETER_SET_HASH_ID, OUTPUT_MODULE_LABEL, CREATION_DATE, CREATE_BY) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO RELEASE_VERSIONS(VERSION) VALUES (?);
INSERT INTO SITES(SITE_NAME) VALUES (?);
INSERT INTO STORAGE_ELEMENTS(SE_NAME) VALUES (?);



SELECT ACQUSITION_ERA_NAME AS CACQUSITION_ERA_NAME FROM ACQUISITION_ERAS
SELECT APP_NAME AS CAPP_NAME FROM APPLICATION_EXECUTABLES
SELECT THIS_FILE_ID AS CTHIS_FILE_ID, ASSOCATED_FILE AS CASSOCATED_FILE FROM ASSOCIATED_FILES
SELECT BLOCK_NAME AS CBLOCK_NAME, PATH_ID AS CPATH_ID, OPEN_FOR_WRITING AS COPEN_FOR_WRITING, ORIGIN_SITE AS CORIGIN_SITE, BLOCK_SIZE AS CBLOCK_SIZE, FILE_COUNT AS CFILE_COUNT, CREATION_DATE AS CCREATION_DATE, CREATE_BY AS CCREATE_BY, LAST_MODIFICATION_DATE AS CLAST_MODIFICATION_DATE, LAST_MODIFIED_BY AS CLAST_MODIFIED_BY FROM BLOCKS
SELECT THIS_BLOCK_ID AS CTHIS_BLOCK_ID, PARENT_BLOCK_ID AS CPARENT_BLOCK_ID FROM BLOCK_PARENTS
SELECT SE_ID AS CSE_ID, BLOCK_ID AS CBLOCK_ID FROM BLOCK_STORAGE_ELEMENTS
SELECT HASH AS CHASH, CONTENT AS CCONTENT FROM BRANCH_HASHES
SELECT DATA_TIER_NAME AS CDATA_TIER_NAME, CREATION_DATE AS CCREATION_DATE, CREATE_BY AS CCREATE_BY FROM DATA_TIERS
SELECT SCHEMA_VERSION AS CSCHEMA_VERSION, DBS_RELEASE_VERSION AS CDBS_RELEASE_VERSION, INSTANCE_NAME AS CINSTANCE_NAME, INSTANCE_TYPE AS CINSTANCE_TYPE, CREATION_DATE AS CCREATION_DATE, LAST_MODIFICATION_DATE AS CLAST_MODIFICATION_DATE FROM DBS_VERSIONS
SELECT LOGICAL_FILE_NAME AS CLOGICAL_FILE_NAME, IS_FILE_VALID AS CIS_FILE_VALID, PATH_ID AS CPATH_ID, BLOCK_ID AS CBLOCK_ID, FILE_TYPE_ID AS CFILE_TYPE_ID, CHECK_SUM AS CCHECK_SUM, EVENT_COUNT AS CEVENT_COUNT, FILE_SIZE AS CFILE_SIZE, BRANCH_HASH_ID AS CBRANCH_HASH_ID, ADLER32 AS CADLER32, MD5 AS CMD5, AUTO_CROSS_SECTION AS CAUTO_CROSS_SECTION, CREATION_DATE AS CCREATION_DATE, CREATE_BY AS CCREATE_BY, LASTMODIFICATIONDATE AS CLASTMODIFICATIONDATE, LAST_MODIFIED_BY AS CLAST_MODIFIED_BY FROM FILES
SELECT RUN_NUM AS CRUN_NUM, LUMI_SECTION_NUM AS CLUMI_SECTION_NUM, FILE_ID AS CFILE_ID FROM FILE_LUMIS
SELECT THIS_FILE_ID AS CTHIS_FILE_ID, PARENT_FILE_ID AS CPARENT_FILE_ID FROM FILE_PARENTS
SELECT FILE_ID AS CFILE_ID, PROCESS_CONFIG_ID AS CPROCESS_CONFIG_ID FROM FILE_PROCESS_CONFIGS
SELECT FILE_TYPE AS CFILE_TYPE FROM FILE_TYPES
SELECT HASH AS CHASH, NAME AS CNAME FROM PARAMETER_SET_HASHES
SELECT PATH_NAME AS CPATH_NAME, IS_PATH_VAILD AS CIS_PATH_VAILD, PRIMARY_DS_ID AS CPRIMARY_DS_ID, PROCESSED_DS_ID AS CPROCESSED_DS_ID, DATA_TIER_ID AS CDATA_TIER_ID, PATH_TYPE_ID AS CPATH_TYPE_ID, ACQUISITION_ERA_ID AS CACQUISITION_ERA_ID, PROCESSING_ERA_ID AS CPROCESSING_ERA_ID, PHYSICS_GROUP_ID AS CPHYSICS_GROUP_ID, XTCROSSSECTION AS CXTCROSSSECTION, GLOBAL_TAG AS CGLOBAL_TAG, CREATIONDATE AS CCREATIONDATE, CREATEBY AS CCREATEBY, LASTMODIFICATIONDATE AS CLASTMODIFICATIONDATE, LASTMODIFIEDBY AS CLASTMODIFIEDBY FROM PATHS
SELECT THIS_PATH_ID AS CTHIS_PATH_ID, PARENT_PATH_ID AS CPARENT_PATH_ID FROM PATH_PARENTS
SELECT PATH_ID AS CPATH_ID, PROCESS_CONFIG_ID AS CPROCESS_CONFIG_ID FROM PATH_PROCESS_CONFIGS
SELECT PATH_ID AS CPATH_ID, RUN_NUMBER AS CRUN_NUMBER, COMPLETE AS CCOMPLETE, EVENT_COUNT AS CEVENT_COUNT, LUMI_SECTION_COUNT AS CLUMI_SECTION_COUNT, CREATION_DATE AS CCREATION_DATE, CREATE_BY AS CCREATE_BY FROM PATH_RUNS
SELECT PATH_TYPE AS CPATH_TYPE FROM PATH_TYPES
SELECT PHYSICS_GROUP_NAME AS CPHYSICS_GROUP_NAME, PHYSICS_GROUP_CONVENER AS CPHYSICS_GROUP_CONVENER FROM PHYSICS_GROUPS
SELECT PRIMARY_DS_NAME AS CPRIMARY_DS_NAME, PRIMARY_DS_TYPE_ID AS CPRIMARY_DS_TYPE_ID, CREATION_DATE AS CCREATION_DATE, CREATE_BY AS CCREATE_BY FROM PRIMARY_DATASETS
SELECT PRIMARY_DS_TYPE AS CPRIMARY_DS_TYPE FROM PRIMARY_DS_TYPES
SELECT PROCESSED_DS_NAME AS CPROCESSED_DS_NAME FROM PROCESSED_DATASETS
SELECT PROCESSING_ERA_NAME AS CPROCESSING_ERA_NAME FROM PROCESSING_ERAS
SELECT APP_EXEC_ID AS CAPP_EXEC_ID, RELEASE_VERSION_ID AS CRELEASE_VERSION_ID, PARAMETER_SET_HASH_ID AS CPARAMETER_SET_HASH_ID, OUTPUT_MODULE_LABEL AS COUTPUT_MODULE_LABEL, CREATION_DATE AS CCREATION_DATE, CREATE_BY AS CCREATE_BY FROM PROCESS_CONFIGURATIONS
SELECT VERSION AS CVERSION FROM RELEASE_VERSIONS
SELECT SITE_NAME AS CSITE_NAME FROM SITES
SELECT SE_NAME AS CSE_NAME FROM STORAGE_ELEMENTS
