alter session set NLS_DATE_FORMAT='yyyy/mm/dd:hh:mi:ssam';

spool mig-4.log;
select sysdate from dual;


ALTER TABLE FILE_OUTPUT_MOD_CONFIGS DROP PRIMARY KEY;

ALTER TABLE FILE_OUTPUT_MOD_CONFIGS DROP constraint TUC_FC_1;

ALTER TABLE FILE_OUTPUT_MOD_CONFIGS DROP constraint FL_FC ;

ALTER TABLE FILE_OUTPUT_MOD_CONFIGS DROP constraint OMC_FC;

DROP index IDX_FC_1;

DROP index IDX_FC_2;


INSERT /*+ append */ INTO FILE_OUTPUT_MOD_CONFIGS(FILE_OUTPUT_CONFIG_ID, FILE_ID, OUTPUT_MOD_CONFIG_ID)
SELECT FA.ID, FA.FILEID, FA.ALGORITHM FROM CMS_DBS_PROD_GLOBAL.FILEALGO FA;
commit;
select 'Done insert FILE_OUPTU_MOD_CONFIGS' from dual;
select sysdate from dual;

CREATE INDEX IDX_FC_1 ON FILE_OUTPUT_MOD_CONFIGS(FILE_ID);

CREATE INDEX IDX_FC_2 ON FILE_OUTPUT_MOD_CONFIGS(OUTPUT_MOD_CONFIG_ID);

ALTER TABLE FILE_OUTPUT_MOD_CONFIGS ADD (
  CONSTRAINT PK_FC
 PRIMARY KEY
 (FILE_OUTPUT_CONFIG_ID)
    USING INDEX ,
  CONSTRAINT TUC_FC_1
 UNIQUE (FILE_ID, OUTPUT_MOD_CONFIG_ID)
    USING INDEX );

ALTER TABLE FILE_OUTPUT_MOD_CONFIGS ADD (
  CONSTRAINT FL_FC
 FOREIGN KEY (FILE_ID)
 REFERENCES FILES (FILE_ID)
    ON DELETE CASCADE,
  CONSTRAINT OMC_FC
 FOREIGN KEY (OUTPUT_MOD_CONFIG_ID)
 REFERENCES OUTPUT_MODULE_CONFIGS (OUTPUT_MOD_CONFIG_ID)
    ON DELETE CASCADE);

select 'Done recreate  FILE_OUTPUT_MOD_CONFIGS constraint' from dual;
select sysdate from dual;

spool off;

